# Generated by Django 2.1.5 on 2019-02-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0088_auto_20190220_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='description_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collectiontranslation',
            name='description_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='description_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
