version: 2.1

defaults: &defaults
  working_directory: /app
  docker:
    - image: docker:17.09.0-ce-git

commands:
  docker-build:
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set version
          command: |
            export SALEOR_VERSION=$(git rev-parse --short HEAD)
            if [ -n "$CIRCLE_TAG" ]; then
              export SALEOR_VERSION=$(git describe --tags)
            fi
            sed -i.bak "s#'dev'#'$SALEOR_VERSION'#" saleor/__init__.py
      - run:
          name: Build application Docker image
          command: |
            docker build \
              --build-arg STATIC_URL=$STATIC_URL \
              -t ${DOCKERCLOUD_REPO:-mirumee/saleor}:latest .

jobs:
  test:
    <<: *defaults
    steps:
      - docker-build
      - run:
        name: Run tests
        command: |
          docker run -d --name db -e POSTGRES_USER=saleor -e POSTGRES_PASSWORD=saleor postgres:9.4-alpine
          docker run --network container:db --rm -e DATABASE_URL ${DOCKERCLOUD_REPO:-mirumee/saleor}:latest pytest
        environment:
          DATABASE_URL: postgres://saleor:saleor@localhost:5432/saleor
  deploy:
    <<: *defaults
    steps:
      - docker-build
      - deploy:
          name: Push Docker image
          command: |
            docker login -u $DOCKERCLOUD_USER -p $DOCKERCLOUD_PASS
            docker tag ${DOCKERCLOUD_REPO:-mirumee/saleor}:latest ${DOCKERCLOUD_REPO:-mirumee/saleor}:$CIRCLE_SHA1
            docker push ${DOCKERCLOUD_REPO:-mirumee/saleor}:$CIRCLE_SHA1
            docker push ${DOCKERCLOUD_REPO:-mirumee/saleor}:latest
      - run:
          name: Deploy saleor-demo
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              apk add --upgrade --no-cache curl libcurl
              sh ./scripts/push_static.sh
              curl -u $DEMO_DEPLOY_KEY: \
                -d build_parameters[CIRCLE_JOB]=deploy \
                https://circleci.com/api/v1.1/project/github/mirumee/saleor-demo/tree/master
            fi
      - run:
          name: Deploy saleor master
          command: |
            apk add --upgrade --no-cache zip py-pip
            pip install awscli
            sh ./scripts/deploy_master.sh > /dev/null 2>&1

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
             ignore: /.*/
            tags:
              only: /demo.*/
